### ISSUE TITLE
Tests teamRouter.spec.js > "POST /teams/:id/prompts" will need tweaking.

### ISSUE THREAD

**Issue by ogrotten** [Lambda-School-Labs/video-journal-for-teams-be#56]
Once #53 and #54 are completed, these tests should be tweaked.

**Comment by TinySquid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tests teamRouter.spec.js > "POST /teams/:id/prompts" will need tweaking.](https://trello.com/c/VXZq1kk6/138-tests-teamrouterspecjs-post-teams-id-prompts-will-need-tweaking)
