### ISSUE TITLE
Documentation for endpoint request bodies are missing

### ISSUE THREAD

**Issue by TinySquid** [Lambda-School-Labs/video-journal-for-teams-be#64]
Need to add documentation for endpoints that require a JSON request body with specific parameters. Need to specify if parameter is optional or required for endpoint functionality.

**Comment by TinySquid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation for endpoint request bodies is missing](https://trello.com/c/wfS8AzgV/133-documentation-for-endpoint-request-bodies-is-missing)

**Comment by ogrotten** [comment]
https://alpacavid-api-doc.netlify.com/
