### ISSUE TITLE
Publish code coverage results

### ISSUE THREAD

**Issue by berniedurfee** [Lambda-School-Labs/video-journal-for-teams-be#85]
Please publish your code coverage results to Code Climate

**Comment by ogrotten** [comment]
We have blockers on this. 

1. https://lambdaschoolstudents.slack.com/archives/GSRJF7LNT/p1581547355072600
2. FE analyzes nothing and reports zero percent.
3. The config examples in the notion guide are problematic. Tweaks to make it work could be leading to the zero percent report.

**Comment by ogrotten** [comment]
Config issues have been cleared up and the report runs on the command line, but none of the numbers show on the badges (neither be or fe)

**Comment by ogrotten** [comment]
Readme displays test coverage of 45%. While this doesn't jive with the jest display of test coverage, it exceeds the 30% threshold.
